### ISSUE TITLE
Main JS file missing?

### ISSUE THREAD

**Issue by jguffey** [jeffbcross/angular-svg-base#1]
Maybe I missed a step, but seems like the bower install command is missing the main JS file. I get a consistent 404 on angular-svg-base/angular-svg-base.js after bower install.

**Comment by t-esch** [comment]
+1
folder src is ignored in bower.json and there is no "./angular-svg-base.js" file in root, either in installed version with bower, nor in the github directory

**Comment by maksimr** [comment]
+1

**Comment by lkduerig** [comment]
+1

**Comment by lkduerig** [comment]
I don't know how this is supposed to install, I just spent the entire afternoon fighting with both bower and git, and this doesn't work as installation instructions claim. If anyone else has trouble, here is a very boring workaround that doesn't involve bower:
1. Go here: https://github.com/jeffbcross/angular-svg-base/blob/master/src/svgDirs.js 
2. Copy the code
3. Save it in a file called svgDirs.js wherever you keep your custom JS
4. Add it to your index.html wherever you have included the rest of your JS files
5. Add the dependancy to app.js as instructed in the readme.

**Comment by soumak77** [comment]
+1 As @lkduerig mentions, I had to manually download source to use this module.  It would be awesome if the bower install was updated to include the source as my build system is heavily dependent upon modules installed from bower and is capable of auto injecting the bower dependencies into my root html.

**Comment by MikaAK** [comment]
To make this bower installable bump the package version in `bower.json` and tag the github repo to `0.0.2` that will allow us to bower install it!

**Comment by aaronbc** [comment]
+1

**Comment by billymoon** [comment]
Looks like this issue could be fixed by this PR https://github.com/jeffbcross/angular-svg-base/pull/2

**Comment by jeffbcross** [comment]
Sorry folks, didn't see this issue. I merged #2 and tagged 0.0.2. If there are further issues, feel free to open an issue and tweet it to me at jeffbcross since I don't see GH notifications in email.
